### ISSUE TITLE
Error Encountered While Installing Python Package

### ISSUE THREAD

**Issue by mdmrah** [dnv-opensource/axtreme#9]
Hi,
I was trying to install the package according to the instructions in https://dnv-opensource.github.io/axtreme/README.html, but I am encountering the following issue:
----------------------------------------------------------------------------------------------------
Using CPython 3.13.1
Creating virtual environment at: .venv
error: Failed to read `--find-links` URL: https://download.pytorch.org/whl/torch
  Caused by: Failed to fetch: `https://download.pytorch.org/whl/torch`
  Caused by: Request failed after 3 retries
  Caused by: error sending request for url (https://download.pytorch.org/whl/torch)
  Caused by: client error (Connect)
  Caused by: invalid peer certificate: UnknownIssuer
--------------------------------------------------------------------------------

I have installed the package by making a wheel file from the project.toml. However, I encountered an error while running the Jupyter notebook tutorials. It seems to be an import error, indicating that the package might not be installed correctly. Here is the error:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 11
      8 from torch.utils.data import DataLoader, RandomSampler
     10 from axtreme.acquisition.qoi_look_ahead import QoILookAhead
---> 11 from axtreme.data import BatchInvariantSampler2d, MinimalDataset, SizableSequentialSampler
     12 from axtreme.plotting.gp_fit import plot_1d_model
     13 from axtreme.qoi import GPBruteForce

File c:\Users\mdmrah\AppData\Local\miniconda3\envs\erd_sra\Lib\site-packages\axtreme\data\__init__.py:3
      1 from .batch_invariant_sampler import BatchInvariantSampler2d
      2 from .dataset import MinimalDataset
----> 3 from .importance_dataset import ImportanceAddedWrapper, ImportanceIndexWrapper
      4 from .multi_dim_batch_sampler import MultiBatchSampler
      5 from .numpy_file_dataset import NumpyFileDataset

File c:\Users\mdmrah\AppData\Local\miniconda3\envs\erd_sra\Lib\site-packages\axtreme\data\importance_dataset.py:23
     21 import torch
     22 from torch.utils.data import Dataset
---> 23 from torch.utils.data.dataset import T_co
     26 class ImportanceIndexWrapper(Dataset[T_co]):
     27     """Wraps an existing dataset, returning part of the item as the importance weight."""

ImportError: cannot import name 'T_co' from 'torch.utils.data.dataset' (c:\Users\mdmrah\AppData\Local\miniconda3\envs\erd_sra\Lib\site-packages\torch\utils\data\dataset.py)
-------------------------------------------------------------------------------------------------------------------------------

**Comment by ClaasRostock** [comment]
Hi @mdmrah ,

the axtreme package does not work with python 3.13 .
The reason being that axtreme depends on torch==2.4.1 and botorch==O.10.0

It seems you are using a conda environment with python 3.13 and botorch 0.11.0 (and likely torch 2.5.1).

Best regards,
Claas
